# vi: se ts=2 sts=2 sw=2 et:

- hosts: all
  remote_user: pi
  tasks:
  - name: Copy healthcheck script
    copy:
      src: healthcheck.sh
      dest: /home/pi/healthcheck.sh
      owner: pi
      mode: 'u+x'
  - name: Schedule healthcheck
    cron:
      name: Perform healthcheck every minute
      user: pi
      job: /home/pi/healthcheck.sh
  - name: Schedule refresh every 8 hours
    cron:
      name: Refresh every 8 hours
      minute: "0"
      hour: "*/8"
      user: pi
      job: DISPLAY=:0.0 xdotool key F5
  - name: Set timezone
    become: true
    timezone:
      name: Europe/Oslo
  - name: Upgrade all packages to the latest version
    become: true
    apt:
      name: "*"
      state: latest
  - name: Ensure packages are present (no install recommends)
    become: true
    apt:
      name: "{{item}}"
      state: present
      install_recommends: no
    with_items:
      - xserver-xorg
      - xinit
      - lightdm
      - unclutter
      - imagemagick
      - bc
  - name: Ensure packages are present (install recommends)
    become: true
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - i3
      - suckless-tools
      - lxterminal
      - vim
      - chromium-browser
      - xdotool
      - tmux
  - name: Disable overscan (raspi-config)
    command: raspi-config nonint do_overscan 1
    become: true
  - name: Set up lightdm configuration directory
    file:
      path: /etc/lightdm/lightdm.conf.d/
      state: directory
      owner: root
      mode: 0755
      recurse: true
  - name: Automatically start x for pi user
    copy:
      src: autologin.conf
      dest: /etc/lightdm/lightdm.conf.d/12-autologin.conf
  - name: Copy statusbar script
    copy:
      src: statusbar.sh
      dest: /home/pi/statusbar.sh
      owner: pi
      mode: 'u+x'
  - name: Ensure i3 config path exists for pi user
    file:
      path: /home/pi/.config/i3/
      state: directory
      owner: pi
  - name: Set up i3 for pi user
    copy:
      src: i3.conf
      dest: /home/pi/.config/i3/config
      owner: pi
  - name: Ensure systemd config path exists for pi user
    file:
      path: /home/pi/.config/systemd/user/
      state: directory
      owner: pi
      recurse: true
  - name: Add chromium systemd unit for pi user
    copy:
      src: chromium.service
      dest: /home/pi/.config/systemd/user/chromium.service
      owner: pi
